Add AccountID on Bank transactions line items
XeroAPI/Xero-OpenAPI pull request #414
Opened 2021-05-14 04:01 UTC by kchandola

This change is adding the field AccountID on the line items for GET bank transactions endpoint.

We are exposing the AccountID for the chart of account associated on the line item. It is not available for GET and not supported for PUT and POST just yet.

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-05-14 15:18 UTC, SerKnight requested changes
Hi Keertika.

I think we have to add it to the `LineItem` object properties for it to deserialize correctly. Also `LineItem` ref is shared across credit notes and invoices but pretty sure this would keep it optional for the other objs.

I can test in SDKs if you can confirm:
```
LineItem:
  externalDocs:
    url: 'https://developer.xero.com/documentation/api/invoices#post'
  properties:
        ...
    AccountID:
      description: The associated account ID related to this line item
      type: string
      format: uuid
      example: "00000000-0000-0000-0000-000000000000"
```

2021-05-14 21:33 UTC, SidneyAllen commented
@kchandola - Chris is correct.  Look at line 23030 in accounting.yaml.  That's the component you'll want to add the AccountID property to.

2021-05-17 00:56 UTC, kchandola commented
Hey @SerKnight @SidneyAllen  I have made the changes here. Please review.
Also @SerKnight this field is only exposed via Bank Transactions endpoint, would you be able to confirm its optional for others, like you mentioned in the comment above.
Thanks

2021-05-17 16:22 UTC, SerKnight commented
Built and confirmed that the `account_id` param is serialized back with bank transactions and not required for the other objects using it.

Thank you 😺  - I will get this OAS version merged and released with a few other small changes today.

<img width="1186" alt="Screen Shot 2021-05-17 at 10 20 24 AM" src="https://user-images.githubusercontent.com/2935387/118522745-a538b100-b6f9-11eb-8415-c838ba782067.png">


<img width="1181" alt="Screen Shot 2021-05-17 at 10 21 11 AM" src="https://user-images.githubusercontent.com/2935387/118522731-9fdb6680-b6f9-11eb-95ea-b6661fbc72b7.png">

2021-05-17 16:22 UTC, SerKnight approved these changes
Tested optional line item account id param

2021-05-18 14:57 UTC, merged